server:
  port: 8081

spring:
  datasource: # Data Source
    url: "jdbc:postgresql://192.168.40.128:5432/db_cdg_estore_promomgt"
    username: postgres
    password: postgres
  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: create
    show-sql: true

codigo:
  codetest:
    evmgtsys:
      server:
        port: 8080
        url: "http://localhost:8080"
        evoucherdef-by-id: "/evoucherdef"