server:
  port: 8082

spring:
  datasource: # Data Source
    url: "jdbc:postgresql://192.168.40.128:5432/db_cdg_idp"
    username: postgres
    password: postgres
  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: create
    show-sql: true

jwt:
  signing:
    key: c2a4911fcecd466eaecba59166988fb4